server:
  port: 8080

spring:
  application:
    name: amisafe
  data:
    mongodb:
      uri: mongodb+srv://dilshankm:zUj4vNysu1ndHcGI@amisafe.9z4sh.mongodb.net/?retryWrites=true&w=majority&appName=amisafe
      database: crime_db

police:
  api:
    url: "https://data.police.uk/api/crimes-street/all-crime?lat=%s&lng=%s&date=%s"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

